name: super_enum_generator
description: Dev-dependency to generate sealed classes and when statements together with the super_enum.dart package.
version: 1.0.0
#homepage: https://github.com/Octacore19/super_enum

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  source_gen: ^1.0.2
  analyzer: '^1.7.1'
  build: '^2.0.2'
  code_builder: ^4.0.0
  dart_style: ^2.0.1

dev_dependencies:
  test: ^1.17.9
  build_runner: ^2.0.5
  source_gen_test: ^1.0.0